# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'kkp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'SnapKit', '~> 4.0.0'
  pod 'KeychainSwift', '~> 11.0'
  pod 'Cache'
  pod 'Alamofire'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'ObjectMapper', '~> 3.3'
  # Pods for kkp

  target 'kkpTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'kkpUITests' do
    inherit! :search_paths
    # Pods for testing

       


  end

end
